# -*- coding: utf-8 -*-
"""Cópia de Trabalho ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPdyZqU8l-pzPL6BmmBhuhvEBQ58dVWT
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('gym_members_exercise_tracking.csv', index_col=False)

dataset

dataset.info()

dataset.columns

from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()

df = dataset

colunas_para_normalizar = [
    'Weight (kg)', 'Max_BPM', 'Avg_BPM',
    'Resting_BPM', 'Calories_Burned', 'Fat_Percentage', 'BMI'
]

df[colunas_para_normalizar] = scaler.fit_transform(df[colunas_para_normalizar])

df

columns = df.select_dtypes(include=['object', 'bool']).columns

columns

from sklearn.preprocessing import OrdinalEncoder

ordinal = OrdinalEncoder()

values_cat = ordinal.fit_transform(df[columns])

df[columns]=values_cat

df

x = df.drop(['Workout_Type'], axis=1)

x

y = df['Workout_Type']

y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

from sklearn.linear_model import LinearRegression

model_regression = LinearRegression()

model_regression.fit(x_train, y_train)

model_regression.coef_

y_predict = model_regression.predict(x_test)

y_predict

from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, y_predict)

from sklearn.metrics import r2_score

r2_score(y_test, y_predict)





